CREATE DATABASE Ph26840_Khan
GO

USE Ph26840_Khan
GO
/*CREATE TABLE SanPham(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(150)
)
GO
*/
CREATE TABLE ThuongHieu(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30)
)
GO
CREATE TABLE MauSac(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30)
)
GO
CREATE TABLE ChatLieu(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30)
)
GO
CREATE TABLE Loai(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30)
)
GO
CREATE TABLE SanPham(
    Id INT PRIMARY KEY IDENTITY(1,1),
	MaSP VARCHAR(10) UNIQUE,
	TenSP NVARCHAR(150),
	IdThuongHieu INT,
	IdMauSac INT,
	IdChatLieu INT, 
	IdLoai INT,
	SoLuong INT,
	GiaNhap DECIMAL(20,0) DEFAULT 0,
	GiaBan DECIMAL(20,0) DEFAULT 0,
	TrangThai INT,
	MoTa NVARCHAR(150)
	FOREIGN KEY (IdThuongHieu) REFERENCES ThuongHieu(Id),
	FOREIGN KEY (IdMauSac) REFERENCES MauSac(Id),
	FOREIGN KEY (IdChatLieu) REFERENCES ChatLieu(Id),
	FOREIGN KEY (IdLoai) REFERENCES Loai(Id)
)
GO

CREATE TABLE [User] (
    ID INT PRIMARY KEY IDENTITY(1,1),
	Ma NVARCHAR(20),
    HoTen NVARCHAR(200),
    Email NVARCHAR(100),
    SoDienThoai NVARCHAR(10),
    DiaChi NVARCHAR(255)
)
CREATE TABLE KhachHang(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30),
	Sdt VARCHAR(30) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL
	
)

CREATE TABLE HoaDon(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdKH UNIQUEIDENTIFIER,
	Ma VARCHAR(20) UNIQUE,
	NgayTao DATE DEFAULT NULL,
	NgayThanhToan DATE DEFAULT NULL,
	NgayShip DATE DEFAULT NULL,
	NgayNhan DATE DEFAULT NULL,
	TinhTrang INT DEFAULT 0,
	TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	Sdt VARCHAR(30) DEFAULT NULL,
	 FOREIGN KEY (IdKH) REFERENCES KhachHang(Id),
	 
)
CREATE TABLE GioHang(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdKH UNIQUEIDENTIFIER,
	IdNV UNIQUEIDENTIFIER,
	Ma VARCHAR(20) UNIQUE,
	NgayTao DATE DEFAULT NULL,
	NgayThanhToan DATE DEFAULT NULL,
	TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	Sdt VARCHAR(30) DEFAULT NULL,
	TinhTrang INT DEFAULT 0
)
GO
CREATE TABLE HoaDonChiTiet(
IdHoaDon UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_HoaDonCT PRIMARY KEY (IdHoaDon,IdChiTietSP),
CONSTRAINT FK1 FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id),
CONSTRAINT FK2 FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id),
)

GO
CREATE TABLE GioHangChiTiet(
IdGioHang UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
DonGiaKhiGiam DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_GioHangCT PRIMARY KEY (IdGioHang,IdChiTietSP),
CONSTRAINT FK1_IdGioHang FOREIGN KEY(IdGioHang) REFERENCES GioHang(Id),
CONSTRAINT FK2_IdChiTietSP FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id),
)
GO
/*
INSERT INTO SanPham VALUES('SP01',N'KHĂN CASHMERE TRƠN XỊN')
INSERT INTO SanPham VALUES('SP02',N'KHĂN CHOÀNG LỤA HÀNG CHÂU ')
INSERT INTO SanPham VALUES('SP03',N'KHĂN CHOÀNG DẠ CASHMERE CAO CẤP')
*/

INSERT INTO ThuongHieu VALUES('TH01',N'Gucci')
INSERT INTO ThuongHieu VALUES('TH02',N'Chanel')
INSERT INTO ThuongHieu VALUES('TH03',N'Dior')

INSERT INTO MauSac VALUES('S01',N'Vàng cam')
INSERT INTO MauSac VALUES('S02',N'Xanh lá')
INSERT INTO MauSac VALUES('S03',N'Đỏ')

INSERT INTO ChatLieu VALUES('CL01',N'Cotton')
INSERT INTO ChatLieu VALUES('CL02',N'Len')
INSERT INTO ChatLieu VALUES('CL03',N'Lụa')

INSERT INTO Loai VALUES('L01',N'Giữ ấm')
INSERT INTO Loai VALUES('L02',N'Che nắng')
INSERT INTO Loai VALUES('L03',N'Du lịch')

INSERT INTO SanPham VALUES ('SP01', N'KHĂN CHOÀNG DẠ CASHMERE CARO 2 MẶT', 1, 1,1,1, 150, 565000, 725000, 1, N'Sang trọng')
INSERT INTO SanPham VALUES ('SP02',N'KHĂN LEN VẠT XÉO THỜI TRANG',2, 2, 2, 2, 135, 657000, 889000, 0, N'Nhẹ nhàng')
INSERT INTO SanPham VALUES ('SP03',N'KHĂN CHOÀNG LINEN THỔ CẨM',3, 3, 3, 3,100, 735000, 980000, 1, N'Cá tính')


SELECT * FROM SanPham
SELECT * FROM ThuongHieu
SELECT * FROM MauSac
SELECT * FROM ChatLieu
SELECT * FROM Loai
